### ISSUE TITLE
Bundle `rz-ghidra` and `jsdec`?

### ISSUE THREAD

**Issue by amritbrar** [flathub/re.rizin.cutter#4]
Out of the box, Cutter gives you a `No Decompiler available` error when opening the Decompiler tab. Bundling `rz-ghidra` and `jsdec` would make Cutter more usable right after install. Either that, or make it clear that plugins are also on Flathub (like [rz-ghidra](https://github.com/flathub/re.rizin.cutter.plugin.rz-ghidra), which I found out way too late).

**Comment by 0pendev** [comment]
I don't know how to make plugins more available.
This is more of a flathub issue. It is pretty clear in the gnome app center
![image](https://user-images.githubusercontent.com/28985038/229618797-4d5c39d7-f1fa-4fee-93e5-93d4f8b817cb.png)

**Comment by 0pendev** [comment]
Also, I remember @karliss pointing out in the project Telegram/mastodon that not everyone wants code written by the NSA preinstalled.

I'll check jsdec when I have the time. Don't know what's the release management for it.

**Comment by 0pendev** [comment]
There is no answer from the original author and I don't understand their expectation. I'll reopen it if some more information comes up.

**Comment by amritbrar** [comment]
Sorry for not responding, I've been really busy.

>  This is more of a flathub issue. It is pretty clear in the gnome app center

That makes sense, I downloaded it off Flathub which doesn't show the add-ons.

> that not everyone wants code written by the NSA preinstalled.

I can understand that.

> I'll check jsdec when I have the time. Don't know what's the release management for it.

That would be cool. I guess it's not that big of a deal since Gnome/KDE software stores will show you the decompilers as add-ons, which you can quickly install.

**Comment by yar2001** [comment]
For anyone using command line flatpack, this will work:
```shell
flatpak install re.rizin.cutter.plugin.rz-ghidra
```
